# Project
version=3.2.3
group=net.anvian.sculkhornid
java_version=25

# Common
minecraft_version=26.1
mod_name=SculkHornMod
mod_author=anvian
mod_id=sculkhornid
license=GPL-3.0
credits=PinhaColada2222
description=Creates an area or distance sonic attack with 2 new horns.
minecraft_version_range=[26.1, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# anvian's lib
anvianslib=1.4.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
